# ===============================
#  Server
# ===============================
server.port=4000

# ===============================
#  Database (PostgreSQL)
# ===============================
#db.url=jdbc:postgresql://webapp:5432/webappdb
db.url=jdbc:postgresql://localhost:5432/umsatz_db
db.user=umsatz_app
db.password=Umsatz
db.schema=gea

# ===============================
#  Hikari pool
# ===============================
db.pool.maximumPoolSize=10
db.pool.minimumIdle=2
db.pool.connectionTimeoutMs=10000
db.pool.idleTimeoutMs=600000
db.pool.maxLifetimeMs=1800000
